version: "3"
services:
  db:
    container_name: postgres-prod
    image: postgres:9.6
    # ports: 
    #   - 5432:5432
    networks: 
      - prod_net_back
    volumes:
      - prod_postgresql:/var/lib/postgresql
      - prod_postgresql_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tasks
    restart: always
  backend:
    container_name: backend-prod
    image: back_prod:build_${BUILD_NUMBER}
    build:
      context: .
      args: 
          - WAR_FILE=../target/tasks-backend.war
          - CONTEXT=tasks-backend
    # ports: 
    #   - 9999:8080
    networks: 
      - prod_net_back
      - prod_net_front
    environment: 
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWD=password
    depends_on: 
      - db
  frontend:
    container_name: frontend-prod
    image: front_prod:build_${BUILD_NUMBER}
    build:
      context: .
      args: 
          - WAR_FILE=../frontend/target/tasks.war
          - CONTEXT=tasks
    ports: 
      - 9999:8080
    networks: 
      - prod_net_front
    environment: 
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - APP_VERSION=build_${BUILD_NUMBER}

networks: 
  prod_net_front:
  prod_net_back:

volumes: 
  prod_postgresql:
  prod_postgresql_data: